### ISSUE TITLE
2009 Mac mini not working

### ISSUE THREAD

**Issue by twinec** [juampapo546/Fan-control#1]
I type the fan command and get the following output:
`cat: /sys/devices/platform/applesmc.768/fan2_label: No such file or directory`
`cat: /sys/devices/platform/applesmc.768/fan3_label: No such file or directory`
`Available fans:`
`  master`
and when I try to control master (example: fan master 80) , it outputs:
`cat: /sys/devices/platform/applesmc.768/fan2_label: No such file or directory`
`cat: /sys/devices/platform/applesmc.768/fan3_label: No such file or directory`
and the fan speed doesn't change

**Comment by JuampiCarosi** [comment]
Interesting, can you test the recently created 2009-mini branch? Follow the instructions at the readme but in the first step run `cd ~/ && git clone https://github.com/juampapo546/fan-control/ -b 2009-mini`
If it doesn't work can you give me the output of `cat /sys/devices/platform/applesmc.768/fan1_label` and `ls /sys/devices/platform/applesmc.768/` please?

**Comment by twinec** [comment]
> Interesting, can you test the recently created 2009-mini branch? Follow the instructions at the readme but in the first step run `cd ~/ && git clone https://github.com/juampapo546/fan-control/ -b 2009-mini`
> If it doesn't work can you give me the output of `cat /sys/devices/platform/applesmc.768/fan1_label` and `ls /sys/devices/platform/applesmc.768/` please?

I downloaded the 2009 mini branch and it worked. Thank you.
