### ISSUE TITLE
 [question] how to handle different hardware ?

### ISSUE THREAD

**Issue by braoult** [juampapo546/Fan-control#10]
In `mbp` source, we have some tests on strings like `exhaust` or `master` to determine if we check for more fans...

Could we instead check for the existence of `/sys/.../fanX_label` to easily find everything and do not make any exceptions ? Code would be easier to understand, we could take off many tests, and rely only on `/sys/` files for valid arguments.

Note: I did simplify the code coz' I want to expand it, for example to allow to modify different  fan variables... If the code structure is easier to read, with functions (no copy/paste/edit of code), it will be easier to add stuff... But it is just an opinion.

**Comment by JuampiCarosi** [comment]
That's a good idea, I was planning to eventually migrating to C and implement stuff like you mentioned, but it would be nice to implement it before.
One thing tho, rn I'm not having that much spare time due to uni and work but I'll be open to review any proposals and merge.

**Comment by braoult** [comment]
OK. I will do. But in a new branch, when mbp is in master, just to make things easy (I could branch my own then, and stop playing with github flawed system).
As you don't have so much time, maybe you could add in README how to download the different versions ?
Or just merge mbp.
Easier ! I don't see any problem (there are, surely), but we need to know the issues to fix them. And mbp branch is not a version that is used by everybody... A merge in master will show the issues at least.

**Comment by JuampiCarosi** [comment]
Already merged into master and deleted mbp :P
