### ISSUE TITLE
What is  'auto'

### ISSUE THREAD

**Issue by plum** [juampapo546/Fan-control#13]
Could you tell me what 'auto' is please?

**Comment by JuampiCarosi** [comment]
Auto mode sets the fan to an uncontrolled state again. It means the OS will control the speed instead of the script

**Comment by plum** [comment]
@JuampiCarosi  Ah, as I suspectred. Thanks for kind reply of confirmation.

And thnaks for offering to all,  your delightfullly  useful script :-)
