### ISSUE TITLE
Line 9 and Line 139 missing '

### ISSUE THREAD

**Issue by attemptingmarsbar** [juampapo546/Fan-control#4]
I am getting a line 9: [: missing ']' 
And
Line 139: [: missing ']'
Output when command 'fan' is used. 
I am also not getting a response in fan control in 'auto' mode.

**Comment by JuampiCarosi** [comment]
What mac do you have?
And can you give me the output of the following command please?
`cat /sys/devices/platform/applesmc.768/fan1_label `

**Comment by Toxic95-Glitch** [comment]
same issue here MacBookPro 8.1

**Comment by JuampiCarosi** [comment]
Can you give me the output of the following command please?
`cat /sys/devices/platform/applesmc.768/fan1_label`

**Comment by Toxic95-Glitch** [comment]
Output = Exhaust

**Comment by JuampiCarosi** [comment]
Can you test the recently created "mbp" branch please?

**Comment by ikout** [comment]
I've tested that with an iMac 11,3 with ODD,HDD and CPU and I don't see the issue anymore and I do see that each fan does change speeds accordingly.

Only if we could setup this to act automatically and it would be perfect, but I'll take it as is now.

Thanks for the work on this.

**Comment by JuampiCarosi** [comment]
Yeah, the issue was a typo when detecting MacBook fans. Usage on iMac shouldn't be affected.
Regarding the automatic feature, for now I don't plan on adding one, and if I ever do it will probably be on something more complex than bash. Might be in a future when I have more experience in C
