### ISSUE TITLE
merge master and mbp ?

### ISSUE THREAD

**Issue by braoult** [juampapo546/Fan-control#9]
I am unsure what `mbp` branch is, compared to `master`.

If `master` has some specificity that mbp does not, would it be possible to list them, so we could merge the whole ?

**Comment by JuampiCarosi** [comment]
It's a branch I created to test the script on a mbp but o don't have one so I was waiting for someone to test it. Seems like nobody's going to test it so I'll merge into master and delete mbp today

**Comment by braoult** [comment]
Do you remember what were the main differences ?

**Comment by JuampiCarosi** [comment]
00d20ed0f5c00296362669c736d040610fc2b3ae

**Comment by braoult** [comment]
I don't think so: This commit was a shell-script fix, unrelated to hardware...

**Comment by JuampiCarosi** [comment]
The bug got triggered by being used in a mbp due to the value of the label

**Comment by braoult** [comment]
So the code was already implemented, this is the test which failed, right ? (`&&` inside or outside `[]`). So it was a shell-script syntax error, this is not the value of the label itself.

My guess: As in your README you say to explicitly set an alias with `sh script`, instead of calling directly a "shebang-ed" script, it could simply be a shell issue (for example if the distribution "sh" is not what you think, of if the user had installed different shells which overrides `sh`).

**Comment by JuampiCarosi** [comment]
Yeah, ig it could be that.
What do you propose to address it? Leave it as it is, drop the `sh script` method or something else?

**Comment by braoult** [comment]
I believe `sh` should be dropped, and the bug report closed (as `mbp` is run by bash now).
